#ifndef DNS_CONSTANTS_H
#define DNS_CONSTANTS_H

#define MIN_DNS_HDR_SIZE   12  
#define MIN_DNS_QNAME_MIN   3  
#define MIN_DNS_QTAIL       4  
#define MIN_DNS_QUESTION   (MIN_DNS_QNAME_MIN + MIN_DNS_QTAIL)   
#define MIN_DNS_MSG_SIZE   (MIN_DNS_HDR_SIZE + MIN_DNS_QUESTION) 
#define MIN_DNS_UDP_SIZE   (MIN_UDP_SIZE + MIN_DNS_MSG_SIZE) 

#endif